kind: Secret
apiVersion: v1
metadata:
  name: {{ .Values.secret.name }} 
stringData:
  cookie: ERLANG_COOKIE
  password: {{ .Values.password }}
  url: amqp://{{- .Values.username -}}:{{- .Values.password -}}@{{- .Values.service.loadbalancer.name }}
  username: {{ .Values.username }}
type: Opaque
